language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install p7zip ; true ; fi

before_script:
  - >
       if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
         cd Project/GNU/CLI/ &&
         curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz | tar --extract --xz --strip-components=1 ;
       fi
  - >
       if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
         cd Project/GNU/CLI/ &&
         curl -O "https://evermeet.cx/ffmpeg/$(curl https://evermeet.cx/ffmpeg/ 2>/dev/null | grep -oe 'ffmpeg-[0-9a-z-]\+.7z')" 2>/dev/null &&
         7za e *.7z ;
       fi
script: sh autogen.sh && ./configure && make && make clone_testing_files && make check
