language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo add-apt-repository -y ppa:mc3man/trusty-media ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y ffmpeg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install ffmpeg ; true ; fi

script: cd Project/GNU/CLI/ && sh autogen.sh && ./configure && make && make clone_testing_files && make check
